### ISSUE TITLE
Generator Source Adapter

### ISSUE THREAD

**Issue by polarene** [HotelsDotCom/bull#158]
The module should take the transformers generated from the Core module and produce source file representations. Those will be compiled as part of the standard build of the client project.
The output could be a `JavaFile` (from Java Poet library) to be written explicitly by the client, or a `Path` where the file has been written: this depends if we want the adapter to be free of side-effects.

- The class package should be customizable or have a default value and it will correspond to a path on disk where the file will be written according to Java convention.
- A base path, where the package directories will be written, should be customizable or have a default value.
- In order to be testable and decoupled from the underlying filesystem, the adapter should be injected with a `java.nio.file.FileSystem`.
- For testing purposes, an in-memory filesystem library could be used such as https://github.com/google/jimfs

To maintain uniformity in this project, a common interface should be extracted from this adapter and the Bytecode Adapter, to anticipate future adapters and to decouple the module's clients from concrete implementations.

This module is intended as internal usage in Bull and should not be referenced directly by clients.

**Comment by fborriello** [comment]
Implemented within the PR: #171
