### ISSUE TITLE
Replace Hamcrest with AssertJ

### ISSUE THREAD

**Issue by polarene** [HotelsDotCom/bull#159]
**Is your feature request related to a problem? Please describe.**
At present, the codebase uses the standard Hamcrest matchers for test assertions. While largely adopted, this library hasn't an expressive API, which works fine for simple assertions but falls short for more complex cases making the code difficult to read, often forcing test authors to write helper methods or classes. Moreover, its extension mechanism is clunky, resulting in very few developers writing custom Matchers.

**Describe the solution you'd like**
A valid alternative exists in the [AssertJ](http://joel-costigliola.github.io/assertj/) library which has a fluent and very expressive API, and covers lots of common complex cases. It's fully compatible with Java 8+ and supports lambdas as assertion callbacks.
The API revolves around static methods `assertThat(obj)` that let you chain one or more assertions fluidly. To get a feeling of it check out the [core features highlight](http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html) page.

My proposal is to replace existing test assertions in BULL using AssertJ, which will provide a powerful and expressive API for complex assertions on objects/JavaBeans (there are a lot of them as test samples) without requiring extra code.

**Comment by fborriello** [comment]
Actually, once this issue will be closed, **AssertJ** will be the default library to be used in BULL for the testing purpose along with **Mockito** for the object mocking and **TestNG** for the data providers.
