### ISSUE TITLE
Use the new "hasPackage" assertion from AssertJ 3.18.0

### ISSUE THREAD

**Issue by polarene** [HotelsDotCom/bull#194]
**Is your feature request related to a problem? Please describe.**
Since the test dependency on AssertJ has been updated to 3.18.0, a new assertion is available to check a Class package:

    Class<?> actual = ...

    assertThat(actual).hasPackage("com.foo.bar");

while previously the best you could do was for example

    assertThat(actual.getName()).startsWith("com.foo.bar");
    // or in Java 9+
    assertThat(actual.getPackageName()).equals("com.foo.bar");

**Describe the solution you'd like**
We should replace the existing usages of assertion on packages with the new one to make the tests more expressive. Currently, the only usages are in `TransformerBytecodeAdapterTest`, in the "transformer-bytecode-adapter" module.

**Comment by fborriello** [comment]
done
