### ISSUE TITLE
Fix race condition imposed by Map interface

### ISSUE THREAD

**Issue by azell** [HotelsDotCom/bull#49]
**Describe the bug**
CacheManagerFactory. CACHE_MAP should have type ConcurrentMap instead of Map.  This would allow the implementation to use the atomic ConcurrentMap.computeIfAbsent method when creating caches instead of Map.get and Map.put.

**Comment by fborriello** [comment]
Thanks @azell, this sound as really good suggestion, I'll implement is ASAP and then put you as reviewer of the PR.
Thanks

**Comment by fborriello** [comment]
@azell please find here the pull request: [PR #50](https://github.com/HotelsDotCom/bull/pull/50)

**Comment by azell** [comment]
I left a couple of comments in code review.  Please feel free to respond.

**Comment by fborriello** [comment]
Thanks a lot for your suggestions, the changes have been applied. Can you please review the PR?

**Comment by fborriello** [comment]
Deat @azell, the change has been implemented, you can find it on version [1.2.6](https://github.com/HotelsDotCom/bull/releases/tag/1.2.6).
Thanks for contributing
