### ISSUE TITLE
Identify the best Java library for source code generation.

### ISSUE THREAD

**Issue by fborriello** [HotelsDotCom/bull#72]
Identify the best Java library for source code generation, the suitable candidates are:

- [Java POET](https://github.com/square/javapoet)
- [JavaParser](https://javaparser.org/)
- [CodeGen](https://github.com/Pyknic/CodeGen)
- [Roaster](https://github.com/forge/roaster)

**Comment by polarene** [comment]
Let's include also [Roaster](https://github.com/forge/roaster) to the candidates.

**Comment by fborriello** [comment]
Let’s also keep an eye on their dependencies, we have to avoid conflict issues in the applications that hosts BULL

**Comment by polarene** [comment]
Following are some considerations on the canditate libs.
I'll start with the negative factors first of those I'd like to rule out:

**JavaParser**
- does too much: it's a parser, analyzer, transformer other than a generator. 
- Focusing on code generation, it doesn't seem to have a nice API.

**CodeGen**
- has only 2 contributors, last release is from 2017
- given example shows a nice API but doesn't show all the features: maybe it's less powerful than the other libs

Talking instead about positive factors these are the favorites:

**JavaPoet**
- fluent and powerful API
- extensive feature set (including Javadoc and formatting)
- many contributors, stars and forks
- not actively developed at the moment but seems feature-complete

**Roaster**
- I had previous experience working with it
- nice API but seems inferior compared to JavaPoet
- fewer contributors than JavaPoet, but it's backed by the Jboss community

All considered I would choose **JavaPoet**.

**Comment by fborriello** [comment]
I do agree with you. If no one has concerns with this library we can go with JavaPoet.
