### ISSUE TITLE
Transformer generation modules setup

### ISSUE THREAD

**Issue by fborriello** [HotelsDotCom/bull#75]
**Description.**

As part of the Transformer Generation project, it is required to set up the project modules.

**Desired solution**

The "Transformer generation" modules have to be built on demand, using a specific maven profile.
This will speed up the process and avoid the build of modules not strictly required.

The modules must have the following hierarchy:

- `bull-transformer-generator-parent`
  - `transformer-generator-core`
  - `transformer-bytecode-adapter`
  - `transformer-generator-registry`
  - `transformer-source-adapter`

The module: `bull-transformer-generator-parent` will have `bean-utils-library-parent` as a parent. 
All the others: 
- `transformer-generator-core`
- `transformer-bytecode-adapter`
- `transformer-generator-registry`
- `transformer-source-adapter`

will have as a parent: `bull-transformer-generator-parent`

**Comment by polarene** [comment]
Actually, the registry is not intended as an adapter but more like a utility component to retrieve the transformers generated from a code base. I would rename the module like `transformer-generator-registry`, what do you think?

**Comment by fborriello** [comment]
@polarene do you mean that the `transformer-registry-adapter` should be renamed in `transformer-generator-registry`?

**Comment by polarene** [comment]
Yes exactly

**Comment by fborriello** [comment]
Done, thanks
